Week3
Vets-Who-Code/js-web-path-bealecs pull request #15
Opened 2023-03-25 20:49 UTC by bealecs

I have committed the week 3 issue document inside of the week 3 folder. Check out the readme for instructions and link to 
 Netlify preview

2023-03-26 20:43 UTC, axecopfire commented on ThirdReadMe.md
> +#### I added a new branch named 'secondary brach' and I will be committing this file to the secondary-branch and then opening the pull request to the main branch from there
This is a really long title

2023-03-26 20:44 UTC, axecopfire commented on ThirdReadMe.md
> +# **Clif Codes**
You don't need to Bold headings

2023-03-26 20:45 UTC, axecopfire commented on Week3/index.html
> +        <navbar style="display: flex; flex-direction: row; justify-content: space-evenly;">
This is supposed to be week3 html, there shouldn't be any CSS. Also, when you do end up using CSS. Please don't use inline CSS. Use a CSS file

2023-03-26 20:46 UTC, axecopfire commented on Week3/index.html
> +    <body>
All content should be nested inside the `<body>`. Only the `<head>` should be outside.

2023-03-26 20:47 UTC, axecopfire commented on Week3/index.html
> +                <th style="text-align: center;">Footer</th>
`<th>` stands for header, seems strange to use as a footer.

2023-03-26 20:48 UTC, axecopfire commented on Week3/index.html
> +    <footer>
`<footer>` needs to be inside `<body>`.

2023-03-26 20:49 UTC, axecopfire requested changes
Check this out for an example with some code that uses `<header>` and `<footer>`

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure#active_learning_exploring_the_code_for_our_example

2023-03-26 21:18 UTC, bealecs commented on Week3/index.html
> +        <navbar style="display: flex; flex-direction: row; justify-content: space-evenly;">
Noted, I will fix that now

2023-03-26 21:18 UTC, bealecs commented on Week3/index.html
> +    <body>
Roger that

2023-03-26 21:19 UTC, bealecs commented on Week3/index.html
> +                <th style="text-align: center;">Footer</th>
Just now realized there is a <tfoot> tag.... I have always used <th> LOL thanks, will also fix now

2023-03-26 21:19 UTC, bealecs commented on Week3/index.html
> +    <footer>
Roger

2023-03-28 16:23 UTC, axecopfire approved these changes
Great job and thanks for working through these comments.

2023-03-28 16:50 UTC, merged