Issue5
Vets-Who-Code/js-web-path-bealecs pull request #17
Opened 2023-03-31 03:40 UTC by bealecs

Issue #5 : Ready for review

2023-03-31 16:50 UTC, axecopfire commented on issue5ReadMe.md
> +> I changed the navbar and footer section to be frames so that I could make them into components. I also added the prototyping as asked in issue 5. Minor changes to UI
Frames are awesome. I need to add that to issue 5. Did you make any components?

2023-03-31 16:52 UTC, axecopfire commented on issue5ReadMe.md
> +> I changed the navbar and footer section to be frames so that I could make them into components. I also added the prototyping as asked in issue 5. Minor changes to UI
Found Navbar and Footer are components

2023-03-31 18:40 UTC, axecopfire commented on issue5ReadMe.md
> + > Contact form is similar to others, Navbar component, footer component
I agree, can you show some examples that you're comparing?

2023-03-31 18:49 UTC, axecopfire commented on issue5ReadMe.md
> + > Check out the Projects page; this law is displayed with grouped together projects that all belong together. You could even argue by using nav list items,
I'm not seeing clear boundaries. I'm just seeing space between, which is law of proximity.

2023-03-31 18:56 UTC, axecopfire commented on issue5ReadMe.md
> + > I try to make my designs aethestically pleasing. I think my favorite section is the project cards
These "cards are basic", there's a lot more you could do with them. Here are some aesthetically pleasing card examples
- https://codepen.io/search/pens?q=cards

I think this UX law is the most difficult to implement since it's subjective. Here are the best portfolios currently on the web. 
- https://www.awwwards.com/websites/portfolio/

Also, this law talks about usability, what about those cards are we trying to use?

2023-03-31 18:58 UTC, axecopfire requested changes
I'd like to see more thought added to the design. I'd like to see some depth and borders. Whether that's a background for a section, or/and some box shadow

2023-04-01 02:57 UTC, bealecs commented on issue5ReadMe.md
> + > Contact form is similar to others, Navbar component, footer component
I would say this is a solid comparison? https://www.w3schools.com/howto/howto_css_contact_form.asp the form for the site will be fairly basic as it is solely a contact form meant to capture name, email, and message. The only differences that are typically found with contact forms is CSS differences or different input methods like phone number or ect.. A familiar contact form is easy to navigate and users know what is expected of them. This is why I associated Jakob's law with the contact form

2023-04-01 02:58 UTC, bealecs commented on issue5ReadMe.md
> + > Check out the Projects page; this law is displayed with grouped together projects that all belong together. You could even argue by using nav list items,
I made a change to a carousel type display for the projects page. This way, the individual projects are still grouped together on the projects page, but a clear boundary is established between each project by use of the carousel.

2023-04-01 03:00 UTC, bealecs commented on issue5ReadMe.md
> + > I try to make my designs aethestically pleasing. I think my favorite section is the project cards
With changing the projects page to a carousel view, I realized that I incorporated Miller's law into the site as well. I decided to kind of swap out this law for the Miller's law application due to the fact that when I was reworking the projects cards, I broke them down and made it a little more simple to digest by changing it to carousel theme. This law is also exhibited by giving the resume and contact form their own pages for viewing.

2023-04-01 15:53 UTC, axecopfire commented on issue5ReadMe.md
> + > Contact form is similar to others, Navbar component, footer component
Please put that context in your README

2023-04-01 15:59 UTC, axecopfire commented on issue5ReadMe.md
> + > Check out the Projects page; this law is displayed with grouped together projects that all belong together. You could even argue by using nav list items,
I'm fine if you want to keep the carousel. Do you have any thoughts on how you're going to implement the carousel in this design? Only reason I'm bringing this up is that carousels aren't a simple solution. I think using clear boundaries like `border` and background differences would be a much simpler solution.

If you are going to use a carousel, use this one https://kenwheeler.github.io/slick/
Slick Slider was made by Ken Wheeler, a board member of Vets Who Code.

2023-04-01 16:08 UTC, axecopfire commented on issue5ReadMe.md
> + > I try to make my designs aethestically pleasing. I think my favorite section is the project cards
There's a tradeoff here. You have removed noise from the interface yes. However, you've created an extra barrier to perusing all of your projects. Now someone is going to have to click through and wait for the animation to finish. How many clicks do you think you'll get out of someone? In which order do you display your projects? Which ones are most and least important? Hiding content can make it feel less important.

2023-04-01 19:41 UTC, axecopfire approved these changes

2023-04-02 01:34 UTC, bealecs commented on issue5ReadMe.md
> + > Contact form is similar to others, Navbar component, footer component
Done

2023-04-02 01:36 UTC, bealecs commented on issue5ReadMe.md
> + > Check out the Projects page; this law is displayed with grouped together projects that all belong together. You could even argue by using nav list items,
That's actually kinda crazy.. I have implemented a carousel once before in one of my previous portfolio iterations.. The carousel library that I implemented was react-slick-slider, and that was before I was a member of Vets Who Code. It was already going to likely be my solution for the carousel slider, but now it definitely will be! That's exciting. Shouts out to Ken!

2023-04-02 01:39 UTC, bealecs commented on issue5ReadMe.md
> + > I try to make my designs aethestically pleasing. I think my favorite section is the project cards
The way I saw it, if the visitor is pressed for time, they really only need to see one project. Like you referred to it, the rest is just noise. My thoughts were that if they saw the first project, maybe visited the repo, liked what they saw, they may be inclined to click through and see other results. That was my interpretation, however, and if you think I should follow a different route I am more than open to doing so. However, to answer your question, I think my most in-depth project is Pips With Paul, so I would probably lead with that

2023-04-02 01:39 UTC, merged