Issue 9 Ready for Review
Vets-Who-Code/js-web-path-bealecs pull request #25
Opened 2023-04-20 18:09 UTC by bealecs

Issue #9 : Ready for review 💯

2023-05-03 01:45 UTC, ozzievargas commented on package.json
> +    "parcel": "latest",
Interesting, I have never seen `"latest"` used before. I have seen version numbers with and without carats, as well as `*`. Was there a particular reason you specified `latest`? Just curious.

2023-05-03 02:48 UTC, ozzievargas requested changes
Overall looks good. Only question I have is the intent of the returned array. if you are supposed to return an array of objects, then changes are needed. If the returned array of strings will suffice, I will convert to an approval.

2023-05-03 02:48 UTC, ozzievargas commented on tsconfig.json
This file + typescript package in package.json validates step `Setup Typescript in your Parceljs project`

2023-05-03 02:48 UTC, ozzievargas commented on tsconfig.json
> +
One thing I like to do is remove all the commented out configuration. At the top of my file in a comment, I would include the link to the tsconfig doc like you have here, and if this sample file exists online, add a link to the sample file for reference. You get to keep your config lean but still quickly access the reference materials needed to make changes.

2023-05-03 02:48 UTC, ozzievargas commented on src/index.tsx
> +        newArr.push(Math.random().toString(36).substring(7));
One thing I did notice is that you declared `myArr` to be an array of objects; however, you pushed a string to the array. As of now I can confirm that the returned value is an array of randomly generated strings. I will put "request changes" for now, but if that was the intent, let me know and I will change that to an approval.

2023-05-04 01:52 UTC, bealecs commented on package.json
> +    "parcel": "latest",
I had seen several people using it on stackOverflow and also Schuster had commented on something in the chat earlier with a picture of how the package.Json looked. He used it too so I switched it over because I thought it would be more convenient ![image](https://user-images.githubusercontent.com/109564941/236092297-8d935387-3d70-4b77-b628-4329f339a98d.png)

2023-05-04 01:54 UTC, bealecs commented on tsconfig.json
I have made changes to return an array of objects. I thought I was doing so before, but was just returning an array of strings, whoops!

2023-05-04 01:56 UTC, bealecs commented on tsconfig.json
> +
Done

2023-05-04 01:57 UTC, bealecs commented on src/index.tsx
> +        newArr.push(Math.random().toString(36).substring(7));
Changed, thanks for the feedback because I was not sure if I was doing the right thing. I believe I am on track now.

2023-05-06 03:56 UTC, ozzievargas commented on package.json
> +    "parcel": "latest",
oh ok cool good to know. I will have to add to my list of todos research the benefits of using "latest."

2023-05-06 03:57 UTC, ozzievargas commented
Looks good. Thank you for taking the time to make the recommended changes.

2023-05-06 03:57 UTC, ozzievargas approved these changes

2023-05-06 04:04 UTC, ozzievargas commented
I did approve because the code submitted met the explicit requirements listed within the issue. However, moving forward we need to make sure that the work being done is also tied to the UI somehow. I spoke with Schuster and a part of the requirement is also to incorporate this work into the client.

One Idea I have is to have a coursework section or page where we can click through and visualize the assignment. For example, for this assignment, maybe we tie the function execution to a button. lets say you create an "Issue 9" form where we can press a button and execute. Maybe on the client we display the list of results (in addition to the console. Or maybe when the user clicks the button, some test shows "Generated x number of objects. See console to view the output." You can make it simple or complex, however you see fit. Feel free to reach out if you have any questions.

2023-05-06 05:00 UTC, closed without merging